-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 09:04:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema arius_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema arius_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arius_database` DEFAULT CHARACTER SET utf8 ;
USE `arius_database` ;

-- -----------------------------------------------------
-- Table `arius_database`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_clientes` (
  `cedula` CHAR(8) NOT NULL,
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `correo_electronico` VARCHAR(60) NOT NULL,
  `telefono1` CHAR(11) NOT NULL,
  `telefono2` CHAR(11) NULL,
  `twitter` VARCHAR(20) NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_departamentos` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_tipos_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_tipos_personal` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `tipo_personal` VARCHAR(60) NOT NULL,
  `id_departamento` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_tipo`),
  INDEX `fk_tb_tipos_personal_tb_departamentos1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_tb_tipos_personal_tb_departamentos1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `arius_database`.`tb_departamentos` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_personal` (
  `cedula` CHAR(8) NOT NULL,
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `correo` VARCHAR(45) NULL,
  `telefono1` CHAR(11) NOT NULL,
  `telefono2` CHAR(11) NULL,
  `direccion` VARCHAR(120) NOT NULL,
  `id_tipo` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`cedula`),
  INDEX `fk_tb_personal_tb_tipo_personal1_idx` (`id_tipo` ASC),
  CONSTRAINT `fk_tb_personal_tb_tipo_personal1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `arius_database`.`tb_tipos_personal` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_mapa_zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_mapa_zonas` (
  `id_codigo` CHAR(4) NOT NULL,
  `cedula` CHAR(8) NOT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `punto_referencia` VARCHAR(250) NULL,
  `hora_operacion_1` CHAR(20) NULL,
  `hora_operacion_2` CHAR(20) NULL,
  `sabado_domingo` VARCHAR(20) NULL,
  `panel_version` VARCHAR(120) NULL,
  `modelo_teclado` VARCHAR(120) NULL,
  `reporta_por` VARCHAR(120) NULL,
  `telefono_assig` CHAR(11) NULL,
  `fecha_instalacion` DATE NOT NULL,
  `cedula_asesor` CHAR(8) NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `ubicacion_panel` VARCHAR(200) NOT NULL,
  `observaciones` VARCHAR(2000) NOT NULL,
  `particiones_sistema` VARCHAR(120) NULL,
  `imei` CHAR(15) NULL,
  `linea_principal` VARCHAR(20) NOT NULL,
  `linea_respaldo` VARCHAR(20) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  INDEX `fk_tb_contrato_tb_clientes1_idx` (`cedula` ASC),
  PRIMARY KEY (`id_codigo`),
  INDEX `fk_tb_mapa_zonas_tb_personal1_idx` (`cedula_asesor` ASC),
  CONSTRAINT `fk_tb_contrato_tb_clientes1`
    FOREIGN KEY (`cedula`)
    REFERENCES `arius_database`.`tb_clientes` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_mapa_zonas_tb_personal1`
    FOREIGN KEY (`cedula_asesor`)
    REFERENCES `arius_database`.`tb_personal` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_servicios_solicitados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_servicios_solicitados` (
  `id_servicio_solicitado` INT NOT NULL AUTO_INCREMENT,
  `id_codigo` CHAR(4) NOT NULL,
  `fecha_solicitud` DATE NOT NULL,
  `motivo` VARCHAR(2000) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_servicio_solicitado`),
  INDEX `fk_tb_servicios_solicitados_tb_mapa_zonas1_idx` (`id_codigo` ASC),
  CONSTRAINT `fk_tb_servicios_solicitados_tb_mapa_zonas1`
    FOREIGN KEY (`id_codigo`)
    REFERENCES `arius_database`.`tb_mapa_zonas` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_visitas` (
  `id_visitas` INT NOT NULL AUTO_INCREMENT,
  `id_codigo` CHAR(4) NOT NULL,
  `id_servicio_solicitado` INT NULL,
  `fecha_visita` DATE NOT NULL,
  `servicio_prestado` VARCHAR(2000) NOT NULL,
  `pendientes` VARCHAR(250) NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_visitas`),
  INDEX `fk_tb_visitas_detalles_tb_mapa_zonas1_idx` (`id_codigo` ASC),
  INDEX `fk_tb_visitas_detalles_tb_servicios_solicitados1_idx` (`id_servicio_solicitado` ASC),
  CONSTRAINT `fk_tb_visitas_detalles_tb_mapa_zonas1`
    FOREIGN KEY (`id_codigo`)
    REFERENCES `arius_database`.`tb_mapa_zonas` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_visitas_detalles_tb_servicios_solicitados1`
    FOREIGN KEY (`id_servicio_solicitado`)
    REFERENCES `arius_database`.`tb_servicios_solicitados` (`id_servicio_solicitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `cedula` CHAR(8) NOT NULL,
  `usuario` VARCHAR(30) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `pregunta1` VARCHAR(60) NOT NULL,
  `respuesta1` VARCHAR(255) NOT NULL,
  `pregunta2` VARCHAR(60) NOT NULL,
  `respuesta2` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tb_usuarios_tb_personal1_idx` (`cedula` ASC),
  CONSTRAINT `fk_tb_usuarios_tb_personal1`
    FOREIGN KEY (`cedula`)
    REFERENCES `arius_database`.`tb_personal` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_zonas` (
  `id_zona` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  `configuracion` VARCHAR(60) NULL,
  `equipos` VARCHAR(40) NOT NULL,
  `id_codigo` CHAR(4) NOT NULL,
  PRIMARY KEY (`id_zona`),
  INDEX `fk_tb_zonas_tb_contratos1_idx` (`id_codigo` ASC),
  CONSTRAINT `fk_tb_zonas_tb_contratos1`
    FOREIGN KEY (`id_codigo`)
    REFERENCES `arius_database`.`tb_mapa_zonas` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_tecnicos_instalacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_tecnicos_instalacion` (
  `id_tecnico_instalacion` INT NOT NULL AUTO_INCREMENT,
  `cedula` CHAR(8) NOT NULL,
  `id_codigo` CHAR(4) NOT NULL,
  INDEX `fk_tb_tecnicos_tb_personal1_idx` (`cedula` ASC),
  PRIMARY KEY (`id_tecnico_instalacion`),
  INDEX `fk_tb_tecnicos_instalacion_tb_mapa_zonas1_idx` (`id_codigo` ASC),
  CONSTRAINT `fk_tb_tecnicos_tb_personal1`
    FOREIGN KEY (`cedula`)
    REFERENCES `arius_database`.`tb_personal` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_tecnicos_instalacion_tb_mapa_zonas1`
    FOREIGN KEY (`id_codigo`)
    REFERENCES `arius_database`.`tb_mapa_zonas` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_tecnicos_visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_tecnicos_visitas` (
  `id_tecnico_visita` INT NOT NULL AUTO_INCREMENT,
  `cedula` CHAR(8) NOT NULL,
  `id_detalle` INT NOT NULL,
  INDEX `fk_tb_tecnicos_visitas_tb_personal1_idx` (`cedula` ASC),
  PRIMARY KEY (`id_tecnico_visita`),
  INDEX `fk_tb_tecnicos_visitas_tb_visitas_detalles1_idx` (`id_detalle` ASC),
  CONSTRAINT `fk_tb_tecnicos_visitas_tb_personal1`
    FOREIGN KEY (`cedula`)
    REFERENCES `arius_database`.`tb_personal` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_tecnicos_visitas_tb_visitas_detalles1`
    FOREIGN KEY (`id_detalle`)
    REFERENCES `arius_database`.`tb_visitas` (`id_visitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `cedula` CHAR(8) NOT NULL,
  `usuario` VARCHAR(30) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `pregunta1` VARCHAR(60) NOT NULL,
  `respuesta1` VARCHAR(255) NOT NULL,
  `pregunta2` VARCHAR(60) NOT NULL,
  `respuesta2` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tb_usuarios_tb_personal1_idx` (`cedula` ASC),
  CONSTRAINT `fk_tb_usuarios_tb_personal1`
    FOREIGN KEY (`cedula`)
    REFERENCES `arius_database`.`tb_personal` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_reportes_diarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_reportes_diarios` (
  `id_reporte_diario` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cedula` CHAR(8) NOT NULL,
  `turno` VARCHAR(20) NOT NULL,
  `ap_sin_clo` VARCHAR(45) NOT NULL,
  `ap_con_clo` VARCHAR(45) NOT NULL,
  `eventualidad_emp` VARCHAR(45) NOT NULL,
  `informado_por` VARCHAR(45) NOT NULL,
  `activaciones` VARCHAR(200) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_reporte_diario`),
  INDEX `fk_tb_reportes_diarios_tb_personal1_idx` (`cedula` ASC),
  CONSTRAINT `fk_tb_reportes_diarios_tb_personal1`
    FOREIGN KEY (`cedula`)
    REFERENCES `arius_database`.`tb_personal` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_rd_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_rd_detalles` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_reporte_diario` INT NOT NULL,
  `id_codigo` CHAR(4) NOT NULL,
  `hora` TIME NOT NULL,
  `evento` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `fk_tb_rd_detalles_tb_reportes_diarios1_idx` (`id_reporte_diario` ASC),
  INDEX `fk_tb_rd_detalles_tb_mapa_zonas1_idx` (`id_codigo` ASC),
  CONSTRAINT `fk_tb_rd_detalles_tb_reportes_diarios1`
    FOREIGN KEY (`id_reporte_diario`)
    REFERENCES `arius_database`.`tb_reportes_diarios` (`id_reporte_diario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_rd_detalles_tb_mapa_zonas1`
    FOREIGN KEY (`id_codigo`)
    REFERENCES `arius_database`.`tb_mapa_zonas` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_reporte_turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_reporte_turnos` (
  `id_reporte_turno` INT NOT NULL AUTO_INCREMENT,
  `id_reporte_diario` INT NOT NULL,
  `tipo_estatus` CHAR(1) NOT NULL,
  `servidor_msj` VARCHAR(45) NOT NULL,
  `radio` VARCHAR(45) NOT NULL,
  `lineas_reportes` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id_reporte_turno`),
  INDEX `fk_tb_reporte_turnos_tb_reportes_diarios1_idx` (`id_reporte_diario` ASC),
  CONSTRAINT `fk_tb_reporte_turnos_tb_reportes_diarios1`
    FOREIGN KEY (`id_reporte_diario`)
    REFERENCES `arius_database`.`tb_reportes_diarios` (`id_reporte_diario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arius_database`.`tb_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arius_database`.`tb_notas` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `id_usuario` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `estatus` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_nota`),
  INDEX `fk_tb_tareas_tb_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tb_tareas_tb_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `arius_database`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
